name: CD a rama deploy (simulado)

on:
  push:
    branches: ["main"]

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Preparar artefacto simple
        run: |
          rm -rf .git .github tests phpunit.xml README.md || true
          mkdir -p build && cp -r . build/ || true

      - name: Publicar en rama deploy
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: deploy
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}